version: "3.9"

services:
  db:
    image: mariadb:10.4
    container_name: paniq_auth_user_db
    environment:
      MYSQL_ROOT_HOST: "${DB_HOST}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_HOST}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db_vol:/var/lib/mysql
#      - ./containers/mariadb/config:/etc/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      default:
        ipv4_address: 172.53.1.4

  app:
    container_name: paniq_auth_user_app
    environment:
      WAIT_HOSTS: db:${DB_PORT}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: on-failure
    volumes:
      - app_vol:/app
    depends_on:
      - db
    networks:
      default:
        ipv4_address: 172.53.1.3

volumes:
  app_vol:
  db_vol:

networks:
  default:
    name: golek_network_br
    external: true